name: Deploy to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # Enables manual trigger

permissions:
  id-token: write  # Allow writing the OIDC token for trusted publishing
  contents: read  # Optional, used for access to the repository content (checkout)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true  # Enable Trusted Publisher (no need for an explicit token)
