name: Deploy to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # Enables manual trigger

jobs:
  deploy:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/project/delphivcl/         
    permissions:
      id-token: write
    steps:                       
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: dist
          
      - name: Publish package to PyPI      
        uses: pypa/gh-action-pypi-publish@release/v1
